name: telekom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  numpad_layout: ^0.0.3

  # App Name, Icon, Splash Screen
  launcher_name: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  isar: ^2.1.4
  isar_flutter_libs: ^2.1.4
  build_runner: ^2.4.11
  shared_preferences: ^2.3.1
  path_provider: ^2.0.15
  logger: ^2.4.0
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

launcher_name:
  default: "Kalbovi Telekom"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  ios: false
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
  linux:
    generate: false

flutter_native_splash:
  background_image: "assets/background/background.png"